// ─── AUTH.JS ──────────────────────────────────────────────────────────────
function loadMembers(){db.ref('members').on('value',function(snap){members={};snap.forEach(function(c){members[c.key]=c.val();});renderMemberList();buildGroupMemSelect();if(userName)buildChatTabs();});}
function renderMemberList(){var ns=Object.keys(members);if(!ns.length){el('memberList').innerHTML='<p style="color:var(--muted);font-size:.83rem;text-align:center;padding:8px">No members yet.</p>';return;}el('memberList').innerHTML=ns.map(function(n){var m=members[n];return'<button class="member-btn" data-mname="'+esc(n)+'">'+avt(n,m.color,34)+'<span>'+esc(n)+'</span>'+(n===ADMIN?'<span style="font-size:.7rem;color:var(--terra);margin-left:auto">Admin</span>':'')+'</button>';}).join('');}
function showPin(name){authMember=name;pinEntry='';el('as1').style.display='none';el('as2').style.display='block';el('asName').textContent=(members[name]&&members[name].pin)?'Hello '+name+'! Enter PIN':'Hi '+name+'! Set your PIN';updDots('pinDots',0);el('pinErr').textContent='';}
function updDots(id,len){el(id).querySelectorAll('.pin-dot').forEach(function(d,i){d.classList.toggle('filled',i<len);});}
function checkPin(){var m=members[authMember];if(!m){el('pinErr').textContent='Not found.';return;}if(!m.pin){db.ref('members/'+authMember+'/pin').set(pinEntry);doLogin(authMember,m.color||'#B8967E');return;}if(String(m.pin)===pinEntry){doLogin(authMember,m.color||'#B8967E');}else{el('pinErr').textContent='Wrong PIN.';pinEntry='';updDots('pinDots',0);}}
function doLogin(name,color){userName=name;userColor=color;localStorage.setItem('fk_name',name);localStorage.setItem('fk_color',color);el('authScreen').classList.add('h');el('userPill').innerHTML=avt(name,color,20)+'<span>'+esc(name)+'</span>';db.ref('members/'+name+'/lastSeen').set(Date.now());loadPersonal();buildPresetTags();buildChatTabs();listenToConvo('family');switchTab('d');setTimeout(function(){renderDashboard('doLogin-timeout');},300);}

// Pin pad — login
document.addEventListener('click',function(e){
  var pk=e.target.closest('[data-k]');if(pk){var k=pk.dataset.k;if(k==='cancel'){el('as2').style.display='none';el('as1').style.display='block';pinEntry='';return;}if(k==='back'){pinEntry=pinEntry.slice(0,-1);updDots('pinDots',pinEntry.length);return;}if(pinEntry.length<4){pinEntry+=k;updDots('pinDots',pinEntry.length);}if(pinEntry.length===4)setTimeout(checkPin,100);return;}
  var pk2=e.target.closest('[data-nk]');if(pk2){var k2=pk2.dataset.nk;if(k2==='cancel'){el('as3').style.display='none';el('as1').style.display='block';newPinEntry='';return;}if(k2==='back'){newPinEntry=newPinEntry.slice(0,-1);updDots('newPinDots',newPinEntry.length);return;}if(newPinEntry.length<4){newPinEntry+=k2;updDots('newPinDots',newPinEntry.length);}return;}
  var mb=e.target.closest('[data-mname]');if(mb&&mb.closest('#memberList')){showPin(mb.dataset.mname);return;}
});

document.addEventListener('DOMContentLoaded',function(){
  el('newMemBtn').addEventListener('click',function(){el('as1').style.display='none';el('as3').style.display='block';newPinEntry='';updDots('newPinDots',0);});
  el('createMemBtn').addEventListener('click',function(){var name=el('newName').value.trim();if(!name){el('newPinErr').textContent='Enter your name.';return;}if(newPinEntry.length<4){el('newPinErr').textContent='Enter a 4-digit PIN.';return;}if(members[name]){el('newPinErr').textContent='Name already taken.';return;}var color=el('newColor').value;db.ref('members/'+name).set({name:name,color:color,pin:newPinEntry,lastSeen:Date.now()});doLogin(name,color);});
  el('userPill').addEventListener('click',function(){el('authScreen').classList.remove('h');el('as1').style.display='block';el('as2').style.display='none';el('as3').style.display='none';});

  el('settingsBtn').addEventListener('click',function(){
    if(!userName){alert('Sign in first!');return;}
    var memberColor=members[userName]?members[userName].color:'#B8967E';
    var inviteUrl='https://proteamforlife-source.github.io/Family-Kitchen/';
    el('settingsBody').innerHTML=
      '<div style="display:flex;align-items:center;gap:12px;margin-bottom:16px"><div style="width:48px;height:48px;border-radius:50%;background:'+memberColor+';display:flex;align-items:center;justify-content:center;color:#fff;font-size:1.3rem;font-weight:700">'+esc(userName.charAt(0).toUpperCase())+'</div><div><div style="font-weight:700;font-size:1rem">'+esc(userName)+'</div><div style="font-size:.78rem;color:var(--muted)">Hearth Member</div></div></div>'+
      '<div style="margin-bottom:14px"><div style="font-size:.8rem;font-weight:700;color:var(--muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:.05em">My Colour</div><div style="display:flex;flex-wrap:wrap;gap:8px">'+MEMBER_COLORS.map(function(c){var sel=c.hex===memberColor;return'<div data-pickcolor="'+c.hex+'" title="'+c.name+'" style="width:36px;height:36px;border-radius:50%;background:'+c.hex+';cursor:pointer;border:3px solid '+(sel?'#2A2218':'transparent')+'"></div>';}).join('')+'</div></div>'+
      '<div style="margin-bottom:14px"><div style="font-size:.8rem;font-weight:700;color:var(--muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:.05em">Change PIN</div><div style="display:flex;gap:8px"><input type="password" id="newPinA" placeholder="New PIN (4 digits)" maxlength="4" style="flex:1;padding:8px 12px;border:1.5px solid var(--border);border-radius:9px;font-size:.88rem;outline:none;font-family:inherit"><input type="password" id="newPinB" placeholder="Confirm PIN" maxlength="4" style="flex:1;padding:8px 12px;border:1.5px solid var(--border);border-radius:9px;font-size:.88rem;outline:none;font-family:inherit"></div><button class="btn" id="savePinBtn" style="margin-top:8px;width:100%;font-size:.85rem;padding:8px">Save New PIN</button><div id="pinMsg" style="font-size:.8rem;margin-top:6px;text-align:center"></div></div>'+
      '<div style="margin-bottom:14px"><div style="font-size:.8rem;font-weight:700;color:var(--muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:.05em">Invite a Family Member</div><div class="invite-box"><p style="font-size:.84rem;margin-bottom:8px;opacity:.9">Share this link:</p><div class="invite-url">'+esc(inviteUrl)+'</div><button class="invite-copy" id="copyInviteBtn">Copy Link</button></div></div>'+
      '<button class="sm sx" id="signOutBtn" style="width:100%;padding:9px;font-size:.85rem">Sign Out</button>';
    el('settingsMod').classList.remove('h');
    // Birthday field
    var bdVal=members[userName]&&members[userName].birthday?members[userName].birthday:'';
    el('settingsBody').insertAdjacentHTML('beforeend','<div style="margin-top:14px"><div style="font-size:.8rem;font-weight:700;color:var(--muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:.05em">My Birthday</div><div style="display:flex;gap:8px"><input type="date" id="myBirthdayInput" value="'+bdVal+'" style="flex:1;padding:8px 12px;border:1.5px solid var(--border);border-radius:9px;font-size:.88rem;outline:none;font-family:inherit"><button class="sm st" id="saveBirthdayBtn" style="padding:8px 14px">Save</button></div></div>');
    el('savePinBtn').addEventListener('click',function(){var a=el('newPinA').value.trim(),b=el('newPinB').value.trim(),msg=el('pinMsg');if(a.length!==4||isNaN(a)){msg.style.color='var(--re)';msg.textContent='PIN must be 4 digits.';return;}if(a!==b){msg.style.color='var(--re)';msg.textContent='PINs do not match.';return;}db.ref('members/'+userName+'/pin').set(a);msg.style.color='var(--sage)';msg.textContent='PIN updated!';el('newPinA').value='';el('newPinB').value='';},{once:true});
    el('copyInviteBtn').addEventListener('click',function(){navigator.clipboard.writeText(inviteUrl).then(function(){el('copyInviteBtn').textContent='Copied!';setTimeout(function(){el('copyInviteBtn').textContent='Copy Link';},2000);});},{once:true});
    el('signOutBtn').addEventListener('click',function(){if(typeof personalRef!=='undefined'&&personalRef){personalRef.off();personalRef=null;}personalData={};localStorage.removeItem('fk_name');localStorage.removeItem('fk_color');userName='';userColor='#B8967E';el('settingsMod').classList.add('h');el('authScreen').classList.remove('h');el('as1').style.display='block';el('as2').style.display='none';el('as3').style.display='none';});
    el('saveBirthdayBtn').addEventListener('click',function(){var bd=el('myBirthdayInput').value;if(!bd)return;db.ref('members/'+userName+'/birthday').set(bd);alert('Birthday saved!');},{once:true});
  });
  el('settingsClose').addEventListener('click',function(){el('settingsMod').classList.add('h');});
});