// ─── CHAT.JS ──────────────────────────────────────────────────────────────
function buildGroupMemSelect(){var w=el('groupMemSelect');if(!w)return;w.innerHTML=Object.keys(members).filter(function(n){return n!==userName;}).map(function(n){var m=members[n];var on=groupSelectedMembers.indexOf(n)>-1;return'<div class="mem-chip'+(on?' on':'')+'" data-gmem="'+esc(n)+'">'+avt(n,m.color,18)+'<span>'+esc(n)+'</span></div>';}).join('');}
function buildChatTabs(){var tabs2=el('chatTabs');if(!tabs2||!userName)return;window._hyCgT=performance.now();console.log('[HYDRATE] ATTACH chatGroups(once) path=chatGroups @'+(window._hyNow?_hyNow():'?')+'ms');db.ref('chatGroups').once('value',function(snap){if(!window._hyCg){window._hyCg=1;var _t=performance.now();console.log('[HYDRATE] FIRST chatGroups(once) @'+(window._hyNow?_hyNow():'?')+'ms dur='+(_t-window._hyCgT).toFixed(1)+'ms len='+(window._hyLen?_hyLen(snap.val()):'?')+' count='+(window._hyCount?_hyCount(snap.val()):'?'));}var groups=[];snap.forEach(function(c){var g=c.val();if(g.members&&g.members[userName])groups.push(g);});var html='<button class="chat-tab'+(currentConvoId==='family'?' on':'')+'" data-conv="family" data-cname="Hearth Chat">Hearth</button>';Object.keys(members).forEach(function(n){if(n===userName)return;var cid=[userName,n].sort().join('_');html+='<button class="chat-tab'+(currentConvoId===cid?' on':'')+'" data-conv="'+esc(cid)+'" data-cname="'+esc(n)+'">'+avt(n,members[n]?members[n].color:'#8A7A6E',16)+'<span>'+esc(n)+'</span></button>';});groups.forEach(function(g){html+='<button class="chat-tab'+(currentConvoId===g.id?' on':'')+'" data-conv="'+esc(g.id)+'" data-cname="'+esc(g.name)+'" data-gid="'+esc(g.id)+'">'+esc(g.name)+'</button>';});html+='<button class="chat-tab" id="newGroupBtn">+ Group</button>';tabs2.innerHTML=html;el('newGroupBtn').addEventListener('click',function(){el('groupMod').classList.remove('h');buildGroupMemSelect();});});}
function listenToConvo(convId){if(chatListeners[convId])return;var ref=db.ref('chats/'+convId).limitToLast(60);var _lt=performance.now();console.log('[HYDRATE] ATTACH chats/'+convId+' path=chats/'+convId+' @'+(window._hyNow?_hyNow():'?')+'ms');var _first=1;ref.on('value',function(snap){if(_first){_first=0;var _t=performance.now();console.log('[HYDRATE] FIRST chats/'+convId+' @'+(window._hyNow?_hyNow():'?')+'ms dur='+(_t-_lt).toFixed(1)+'ms len='+(window._hyLen?_hyLen(snap.val()):'?')+' count='+(window._hyCount?_hyCount(snap.val()):'?'));}if(currentConvoId!==convId)return;var msgs=[];snap.forEach(function(c){msgs.push(c.val());});renderMsgs(msgs);});chatListeners[convId]=ref;}
function switchConvo(convId,convName,gid){currentConvoId=convId;currentConvoName=convName;el('chatTitle').innerHTML=(gid?'<button data-addmembers="'+esc(gid)+'" style="background:rgba(255,255,255,.25);border:none;color:#fff;font-size:.72rem;padding:3px 8px;border-radius:8px;cursor:pointer;margin-right:6px">+ Members</button>':'')+esc(convName);el('chatMessages').innerHTML='<div style="text-align:center;color:var(--muted);font-size:.8rem;padding:20px">Loading...</div>';el('chatTabs').querySelectorAll('.chat-tab').forEach(function(t){t.classList.toggle('on',t.dataset.conv===convId);});listenToConvo(convId);if(userName)db.ref('personal/'+userName+'/lastRead/'+convId).set(Date.now());}
function renderMsgs(msgs){var c=el('chatMessages');if(!msgs.length){c.innerHTML='<div style="text-align:center;color:var(--muted);font-size:.8rem;padding:20px">No messages yet. Say hi!</div>';return;}c.innerHTML=msgs.map(function(m){var mine=m.by===userName;var content=m.photo?'<img class="msg-img" src="'+esc(m.photo)+'" data-viewimg="'+esc(m.photo)+'" alt="photo">':'<div class="msg-text">'+esc(m.text)+'</div>';return'<div class="msg-bubble'+(mine?' mine':' theirs')+'">'+content+'<div class="msg-meta">'+(mine?'':('<span style="color:'+(m.color||'#8A7A6E')+';font-weight:600">'+esc(m.by)+'</span> - '))+new Date(m.ts).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'})+'</div></div>';}).join('');c.scrollTop=c.scrollHeight;}
function sendMsg(){var v=el('chatInp').value.trim();if(!v||!userName)return;db.ref('chats/'+currentConvoId).push({text:v,by:userName,color:userColor,ts:Date.now()});el('chatInp').value='';}
function buildAddMembersSelect(){var w=el('addMembersSelect');if(!w)return;var available=Object.keys(members).filter(function(n){return n!==userName&&!addMembersCurrent[n];});if(!available.length){w.innerHTML='<p style="color:var(--muted);font-size:.84rem">All members already in this group!</p>';return;}w.innerHTML=available.map(function(n){var m=members[n];var on=addMembersSelected.indexOf(n)>-1;return'<div class="mem-chip'+(on?' on':'')+'" data-addmem="'+esc(n)+'">'+avt(n,m.color,18)+'<span>'+esc(n)+'</span></div>';}).join('');}
function openAddMembers(gid){db.ref('chatGroups/'+gid).once('value',function(snap){var g=snap.val();if(!g)return;addMembersGid=gid;addMembersCurrent=g.members||{};el('addMembersTitle').textContent='Add to '+g.name;buildAddMembersSelect();el('addMembersMod').classList.remove('h');});}

document.addEventListener('DOMContentLoaded',function(){
  el('chatToggle').addEventListener('click',function(){el('chatPanel').classList.toggle('open');});
  el('chatClose').addEventListener('click',function(){el('chatPanel').classList.remove('open');});
  el('chatSend').addEventListener('click',sendMsg);
  el('chatInp').addEventListener('keydown',function(e){if(e.key==='Enter')sendMsg();});
  el('chatPhotoInp').addEventListener('change',function(){var file=this.files[0];if(!file||!userName)return;var reader=new FileReader();reader.onload=function(ev){db.ref('chats/'+currentConvoId).push({photo:ev.target.result,by:userName,color:userColor,ts:Date.now(),text:'photo'});};reader.readAsDataURL(file);this.value='';});
  el('groupCancel').addEventListener('click',function(){el('groupMod').classList.add('h');groupSelectedMembers=[];});
  el('groupCreate').addEventListener('click',function(){var name=el('groupName').value.trim();if(!name){alert('Enter a group name.');return;}if(groupSelectedMembers.length===0){alert('Select at least one member.');return;}var gid='g'+Date.now(),mems={};mems[userName]=true;groupSelectedMembers.forEach(function(m){mems[m]=true;});db.ref('chatGroups/'+gid).set({id:gid,name:name,members:mems,by:userName});el('groupMod').classList.add('h');el('groupName').value='';groupSelectedMembers=[];buildChatTabs();switchConvo(gid,name,gid);el('chatPanel').classList.add('open');});
  el('addMembersCancel').addEventListener('click',function(){el('addMembersMod').classList.add('h');addMembersSelected=[];});
  el('addMembersSave').addEventListener('click',function(){if(!addMembersGid||!addMembersSelected.length){alert('Select at least one member.');return;}var updates={};addMembersSelected.forEach(function(n){updates[n]=true;});db.ref('chatGroups/'+addMembersGid+'/members').update(updates);el('addMembersMod').classList.add('h');addMembersSelected=[];buildChatTabs();alert('Members added!');});
});