// ─── MYPAGE.JS ────────────────────────────────────────────────────────────
// KEY CHANGE: loadPersonal now triggers planner re-render when planner tab is active
// Planner has its own Firebase listener — personal writes must not trigger planner rerenders
// future: when personal context summaries land in day detail, wire them via plannerDetailCtx refresh only
function loadPersonal(){if(!userName)return;db.ref('personal/'+userName).on('value',function(snap){personalData=snap.val()||{};if(el('pg-m').classList.contains('on'))renderMyPage();if(el('pg-d').classList.contains('on'))renderDashboard();if(el('pg-c').classList.contains('on'))renderCalendar();});}
function savePers(path,val){if(!userName)return;db.ref('personal/'+userName+'/'+path).set(val);}

function renderMyPage(){
  if(!userName){el('myPage').innerHTML='<div class="emp"><span>👤</span>Sign in first!</div>';return;}
  var today=todayKey(),quote=personalData.quote||QUOTES[Math.floor(Math.random()*QUOTES.length)];
  var viewToggle='<div style="display:flex;gap:6px;margin-bottom:12px;background:#fff;border-radius:10px;padding:5px;border:1px solid var(--border)">'+['day','week','month'].map(function(v){return'<button class="sm'+(myPageView===v?' st':' sx')+'" style="flex:1;border-radius:7px" data-mypageview="'+v+'">'+{day:'Day',week:'Week',month:'Month'}[v]+'</button>';}).join('')+'</div>';
  var syncNotice='<div class="cal-sync-notice"><svg width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 22C6.48 22 2 17.52 2 12S6.48 2 12 2s10 4.48 10 10-4.48 10-10 10zm-1-7h2v2h-2zm0-8h2v6h-2z" fill="currentColor"/></svg>Add here once — appears automatically in Planner &amp; Dashboard</div>';
  var todos=personalData.todos?Object.values(personalData.todos):[];
  var todoHtml='<div class="sbox"><h3>To-Do List</h3><div style="display:flex;gap:7px;margin-bottom:10px"><input type="text" id="todoInp" placeholder="Add a task..." style="flex:1;padding:8px 11px;border:1.5px solid var(--border);border-radius:9px;font-size:.88rem;outline:none;font-family:inherit"><button class="sm st" id="todoAddBtn">Add</button></div>'+(todos.length?todos.map(function(t){return'<div style="display:flex;align-items:center;gap:8px;padding:7px 0;border-bottom:1px solid var(--border)"><input type="checkbox" class="shopchk" '+(t.done?'checked':'')+' data-todoid="'+t.id+'"><span style="flex:1;font-size:.88rem;'+(t.done?'text-decoration:line-through;color:var(--muted)':'')+'">'+esc(t.text)+'</span><button class="xbtn" data-deltodo="'+t.id+'">x</button></div>';}).join(''):'<div style="color:var(--muted);font-size:.84rem;padding:8px 0">No tasks yet!</div>')+'</div>';
  var grid='',navHtml='';
  if(myPageView==='day'){
    var dayDate=new Date();dayDate.setDate(dayDate.getDate()+weekOffset);var dk=lKey(dayDate);
    navHtml='<div class="wnav"><button id="prevWk">Prev</button><span>'+dayDate.toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long'})+'</span><button id="nextWk">Next</button></div>';
    var dayItems=(personalData.days&&personalData.days[dk]&&personalData.days[dk].items)?Object.values(personalData.days[dk].items):[];
    var typeLabels={B:'Breakfast',L:'Lunch',S:'Snack',work:'Work',uni:'Uni',appt:'Appointment',workout:'Workout'};
    grid=syncNotice+'<div class="card" style="'+(dk===today?'border-color:var(--terra)':'')+'">'+(!dayItems.length?'<div style="color:var(--muted);font-size:.84rem;padding:8px">Nothing planned.</div>':['work','uni','appt','workout','B','L','S'].map(function(type){var items=dayItems.filter(function(x){return x.type===type;});if(!items.length)return'';return'<div style="margin-bottom:10px"><div style="font-size:.75rem;font-weight:700;color:var(--muted);text-transform:uppercase;margin-bottom:5px">'+(typeLabels[type]||type)+'</div>'+items.map(function(item){return'<div class="mpill mp-'+type+'" style="display:flex;justify-content:space-between;padding:6px 9px;margin-bottom:4px;border-radius:8px"><span>'+esc(item.text)+'</span><button class="xbtn" data-dday="'+item.id+'" data-dk="'+dk+'">x</button></div>';}).join('')+'</div>';}).join(''))+'<button class="sbtn" style="width:100%;font-size:.83rem;padding:7px" data-addd="'+dk+'">+ Add to this day</button></div>';
  } else if(myPageView==='week'){
    var dates=getWeekDates(weekOffset),ws=dates[0],we=dates[6];
    navHtml='<div class="wnav"><button id="prevWk">Prev</button><span>'+ws.toLocaleDateString('en-AU',{day:'numeric',month:'short'})+' - '+we.toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})+'</span><button id="nextWk">Next</button></div>';
    function pill(type,text,id,dk){var short=text.length>10?text.slice(0,10)+'...':text;return'<div class="mpill mp-'+type+'">'+esc(short)+'<button class="xbtn" style="font-size:.52rem;padding:0 2px" data-dday="'+id+'" data-dk="'+dk+'">x</button></div>';}
    grid=syncNotice+'<div class="wgrid">'+dates.map(function(d,i){var dk=lKey(d),isT=dk===today,dayItems=(personalData.days&&personalData.days[dk]&&personalData.days[dk].items)?Object.values(personalData.days[dk].items):[];var bI=dayItems.filter(function(x){return x.type==='B';}),lI=dayItems.filter(function(x){return x.type==='L';}),sI=dayItems.filter(function(x){return x.type==='S';}),cI=dayItems.filter(function(x){return['work','uni','appt','workout'].indexOf(x.type)>-1;});function rp(arr){return arr.map(function(x){return pill(x.type,x.text,x.id,dk);}).join('');}return'<div class="dcard'+(isT?' tod':'')+'"><h4>'+DAYS[i]+'</h4><div class="ddate">'+d.getDate()+'/'+(d.getMonth()+1)+'</div>'+rp(cI)+'<div class="slothdr">B</div>'+rp(bI)+'<div class="slothdr">L</div>'+rp(lI)+'<div class="slothdr">S</div>'+rp(sI)+'<button class="addpill" data-addd="'+dk+'">+</button></div>';}).join('')+'</div>';
  } else {
    var mdata=getMonthDates(monthOffset);
    navHtml='<div class="wnav"><button id="prevWk">Prev</button><span>'+mdata.label+'</span><button id="nextWk">Next</button></div>';
    var firstDay=mdata.days[0].getDay();if(firstDay===0)firstDay=7;
    grid=syncNotice+'<div style="display:grid;grid-template-columns:repeat(7,1fr);gap:3px;margin-bottom:13px">'+['M','T','W','T','F','S','S'].map(function(d){return'<div style="text-align:center;font-size:.65rem;font-weight:700;color:var(--muted);padding:3px">'+d+'</div>';}).join('');
    for(var ei=1;ei<firstDay;ei++)grid+='<div></div>';
    mdata.days.forEach(function(d){var dk=lKey(d),isT=dk===today,dayItems=(personalData.days&&personalData.days[dk]&&personalData.days[dk].items)?Object.values(personalData.days[dk].items):[];grid+='<div style="background:#fff;border-radius:7px;padding:4px;border:1.5px solid '+(isT?'var(--terra)':'var(--border)')+';min-height:44px;cursor:pointer" data-addd="'+dk+'"><div style="font-size:.65rem;font-weight:700;color:'+(isT?'var(--terra)':'var(--muted)')+'">'+d.getDate()+'</div>'+dayItems.slice(0,2).map(function(item){return'<div style="font-size:.55rem;background:var(--cream);border-radius:3px;padding:1px 3px;margin-top:1px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(item.text)+'</div>';}).join('')+(dayItems.length>2?'<div style="font-size:.52rem;color:var(--muted)">+'+(dayItems.length-2)+' more</div>':'')+'</div>';});
    grid+='</div>';
  }
  var wgk='goals_'+(myPageView==='week'?lKey(getWeekDates(weekOffset)[0]):today),wwk='workout_'+(myPageView==='week'?lKey(getWeekDates(weekOffset)[0]):today);
  var goals=(personalData.goals||{})[wgk]||'',workout=(personalData.workout||{})[wwk]||'';
  var myr=personalData.myRecipes?Object.values(personalData.myRecipes):[];
  var prHtml='<div class="ptitle" style="margin-top:7px">My Private Recipes</div><div class="aform"><h3>Add Private Recipe</h3><div class="frow"><input id="prName" type="text" placeholder="Recipe name"><select id="prCat">'+PRESET_CATS.map(function(c){return'<option>'+c+'</option>';}).join('')+'</select><input id="prTags" type="text" placeholder="Tags"><input id="prIngs" type="text" placeholder="Ingredients"><textarea id="prSteps" placeholder="Method"></textarea><button class="btn" data-addpr="1">Save My Recipe</button></div></div>'+(myr.length?myr.map(function(r){return'<div class="rc"><div style="display:flex;justify-content:space-between;align-items:flex-start"><div style="flex:1"><b>'+esc(r.name)+'</b><div style="font-size:.74rem;color:var(--muted);margin-top:2px">'+esc(r.cat)+'</div></div><div style="display:flex;gap:3px"><button class="sm ss" data-shrpr="'+r.id+'" style="font-size:.7rem">Share</button><button class="xbtn" data-delpr="'+r.id+'">x</button></div></div><div class="rbtns"><button class="obn" data-togpr="'+r.id+'">View</button><button class="obn obt" data-cookpr="'+r.id+'">Cook</button><button class="obn obs" data-editpr="'+r.id+'">Edit</button></div><div class="eform" id="pef-'+r.id+'"><input type="text" id="pen-'+r.id+'" value="'+esc(r.name)+'"><select id="pec-'+r.id+'">'+PRESET_CATS.map(function(c){return'<option'+(r.cat===c?' selected':'')+'>'+c+'</option>';}).join('')+'</select><input type="text" id="pet-'+r.id+'" value="'+esc((r.tags||[]).join(', '))+'" placeholder="Tags"><input type="text" id="pei-'+r.id+'" value="'+esc((r.ings||[]).join(', '))+'"><textarea id="pes-'+r.id+'">'+esc(r.steps||'')+'</textarea><div style="display:flex;gap:6px"><button class="sm st" data-savepr="'+r.id+'">Save</button><button class="sm sx" data-cancelpr="'+r.id+'">Cancel</button></div></div><div class="rbody" id="prb-'+r.id+'">'+(r.ings&&r.ings.length?'<h4>Ingredients</h4><ul>'+r.ings.map(function(i){return'<li>'+esc(i)+'</li>';}).join('')+'</ul>':'')+(r.steps?'<h4>Method</h4><p>'+esc(r.steps)+'</p>':'')+'</div></div>';}).join(''):'<div class="emp"><span>📒</span>No private recipes yet!</div>');
  el('myPage').innerHTML='<div class="qbox"><div class="qtxt">"'+esc(quote.q)+'"</div><div class="qauth">-- '+esc(quote.a)+'</div><div class="qbtns"><button class="qbtn" id="newQBtn">New Quote</button><button class="qbtn" id="myQBtn">My Own</button></div></div>'+viewToggle+navHtml+grid+todoHtml+'<div class="sbox"><h3>Goals</h3><textarea id="goalsTA" placeholder="This week I want to...">'+esc(goals)+'</textarea><button class="sbtn" id="saveGoals" style="margin-top:7px;padding:7px 13px;font-size:.83rem">Save Goals</button></div><div class="sbox"><h3>Workout Plan</h3><textarea id="workoutTA" placeholder="Plan your workouts...">'+esc(workout)+'</textarea><button class="sbtn" id="saveWorkout" style="margin-top:7px;padding:7px 13px;font-size:.83rem">Save Plan</button></div>'+prHtml;
  el('prevWk').addEventListener('click',function(){if(myPageView==='month'){monthOffset--;}else{weekOffset--;}renderMyPage();});
  el('nextWk').addEventListener('click',function(){if(myPageView==='month'){monthOffset++;}else{weekOffset++;}renderMyPage();});
  el('newQBtn').addEventListener('click',function(){savePers('quote',QUOTES[Math.floor(Math.random()*QUOTES.length)]);});
  el('myQBtn').addEventListener('click',function(){var q=prompt('Your quote:'),a=prompt('Author:');if(q)savePers('quote',{q:q,a:a||'Me'});});
  el('saveGoals').addEventListener('click',function(){var gs=personalData.goals||{};gs[wgk]=el('goalsTA').value;savePers('goals',gs);alert('Goals saved!');});
  el('saveWorkout').addEventListener('click',function(){var wk2=personalData.workout||{};wk2[wwk]=el('workoutTA').value;savePers('workout',wk2);alert('Saved!');});
  el('todoAddBtn').addEventListener('click',function(){var v=el('todoInp').value.trim();if(!v)return;var tid='t'+Date.now();db.ref('personal/'+userName+'/todos/'+tid).set({id:tid,text:v,done:false});el('todoInp').value='';});
  el('todoInp').addEventListener('keydown',function(e){if(e.key==='Enter')el('todoAddBtn').click();});
}

function saveDayItem(){var type=el('dayModType').value,text=el('dayModInp').value.trim();if(!text)return;var dk=dayCtx.dk,id='i'+Date.now();db.ref('personal/'+userName+'/days/'+dk+'/items/'+id).set({id:id,text:text,type:type});el('dayMod').classList.add('h');el('dayModInp').value='';}

document.addEventListener('DOMContentLoaded',function(){
  el('dayModCancel').addEventListener('click',function(){el('dayMod').classList.add('h');});
  el('dayModSave').addEventListener('click',saveDayItem);
  el('dayModInp').addEventListener('keydown',function(e){if(e.key==='Enter')saveDayItem();});
});